package com.udanti.sales.dao;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesItem generated by hbm2java
 */
@Entity
@Table(name = "sales_item", catalog = "udnati")
public class SalesItem implements java.io.Serializable {

	private int salesItemId;
	private SalesHeader salesHeader;
	private String material;
	private String batch;
	private String materialGroup;
	private String description;
	private String itemCategory;
	private String relevantForBilling;
	private String higherLevelItem;
	private String alternativeToItem;
	private String reasonForRejection;
	private String baseUnitMeasure;
	private Integer roundingQty;
	private String purchaseOrderItem;
	private String quantityIsFixed;
	private String division;
	private String businessArea;
	private BigDecimal netValue;
	private Integer orderQuantity;
	private BigDecimal grossWeight;
	private BigDecimal netWeight;
	private String weightUnit;
	private BigDecimal volume;
	private String deliveryPriority;
	private String plant;
	private String storageLocation;
	private String shippingPoint;
	private String receivingPoint;
	private String route;
	private Date createdOn;
	private String createdBy;
	private String taxClassification;
	private Date varProcessingTime;
	private String returns;
	private String cashDiscount;
	private String availabilityCheck;
	private String volumeRebateGroup;
	private String commissionGroup;
	private String eanNumber;
	private String pricing;
	private Integer minimumDeliveryQty;
	private Date changedOn;
	private String profitCenter;
	private BigDecimal creditPrice;
	private String partialRelease;
	private String manualPrice;
	private String paymtGuarantee;
	private String guaranteed;
	private String costCenter;
	private String modificationAllowed;
	private String cancellationAllowed;

	public SalesItem() {
	}

	public SalesItem(int salesItemId) {
		this.salesItemId = salesItemId;
	}

	public SalesItem(int salesItemId, SalesHeader salesHeader, String material,
			String batch, String materialGroup, String description,
			String itemCategory, String relevantForBilling,
			String higherLevelItem, String alternativeToItem,
			String reasonForRejection, String baseUnitMeasure,
			Integer roundingQty, String purchaseOrderItem,
			String quantityIsFixed, String division, String businessArea,
			BigDecimal netValue, Integer orderQuantity, BigDecimal grossWeight,
			BigDecimal netWeight, String weightUnit, BigDecimal volume,
			String deliveryPriority, String plant, String storageLocation,
			String shippingPoint, String receivingPoint, String route,
			Date createdOn, String createdBy, String taxClassification,
			Date varProcessingTime, String returns, String cashDiscount,
			String availabilityCheck, String volumeRebateGroup,
			String commissionGroup, String eanNumber, String pricing,
			Integer minimumDeliveryQty, Date changedOn, String profitCenter,
			BigDecimal creditPrice, String partialRelease, String manualPrice,
			String paymtGuarantee, String guaranteed, String costCenter,
			String modificationAllowed, String cancellationAllowed) {
		this.salesItemId = salesItemId;
		this.salesHeader = salesHeader;
		this.material = material;
		this.batch = batch;
		this.materialGroup = materialGroup;
		this.description = description;
		this.itemCategory = itemCategory;
		this.relevantForBilling = relevantForBilling;
		this.higherLevelItem = higherLevelItem;
		this.alternativeToItem = alternativeToItem;
		this.reasonForRejection = reasonForRejection;
		this.baseUnitMeasure = baseUnitMeasure;
		this.roundingQty = roundingQty;
		this.purchaseOrderItem = purchaseOrderItem;
		this.quantityIsFixed = quantityIsFixed;
		this.division = division;
		this.businessArea = businessArea;
		this.netValue = netValue;
		this.orderQuantity = orderQuantity;
		this.grossWeight = grossWeight;
		this.netWeight = netWeight;
		this.weightUnit = weightUnit;
		this.volume = volume;
		this.deliveryPriority = deliveryPriority;
		this.plant = plant;
		this.storageLocation = storageLocation;
		this.shippingPoint = shippingPoint;
		this.receivingPoint = receivingPoint;
		this.route = route;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.taxClassification = taxClassification;
		this.varProcessingTime = varProcessingTime;
		this.returns = returns;
		this.cashDiscount = cashDiscount;
		this.availabilityCheck = availabilityCheck;
		this.volumeRebateGroup = volumeRebateGroup;
		this.commissionGroup = commissionGroup;
		this.eanNumber = eanNumber;
		this.pricing = pricing;
		this.minimumDeliveryQty = minimumDeliveryQty;
		this.changedOn = changedOn;
		this.profitCenter = profitCenter;
		this.creditPrice = creditPrice;
		this.partialRelease = partialRelease;
		this.manualPrice = manualPrice;
		this.paymtGuarantee = paymtGuarantee;
		this.guaranteed = guaranteed;
		this.costCenter = costCenter;
		this.modificationAllowed = modificationAllowed;
		this.cancellationAllowed = cancellationAllowed;
	}

	@Id
	@Column(name = "sales_item_id", unique = true, nullable = false)
	public int getSalesItemId() {
		return this.salesItemId;
	}

	public void setSalesItemId(int salesItemId) {
		this.salesItemId = salesItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sales_number")
	public SalesHeader getSalesHeader() {
		return this.salesHeader;
	}

	public void setSalesHeader(SalesHeader salesHeader) {
		this.salesHeader = salesHeader;
	}

	@Column(name = "material", length = 18)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "batch", length = 10)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "material_group", length = 9)
	public String getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}

	@Column(name = "description", length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "item_category", length = 4)
	public String getItemCategory() {
		return this.itemCategory;
	}

	public void setItemCategory(String itemCategory) {
		this.itemCategory = itemCategory;
	}

	@Column(name = "relevant_for_billing", length = 1)
	public String getRelevantForBilling() {
		return this.relevantForBilling;
	}

	public void setRelevantForBilling(String relevantForBilling) {
		this.relevantForBilling = relevantForBilling;
	}

	@Column(name = "higher_level_item", length = 6)
	public String getHigherLevelItem() {
		return this.higherLevelItem;
	}

	public void setHigherLevelItem(String higherLevelItem) {
		this.higherLevelItem = higherLevelItem;
	}

	@Column(name = "alternative_to_item", length = 6)
	public String getAlternativeToItem() {
		return this.alternativeToItem;
	}

	public void setAlternativeToItem(String alternativeToItem) {
		this.alternativeToItem = alternativeToItem;
	}

	@Column(name = "reason_for_rejection", length = 2)
	public String getReasonForRejection() {
		return this.reasonForRejection;
	}

	public void setReasonForRejection(String reasonForRejection) {
		this.reasonForRejection = reasonForRejection;
	}

	@Column(name = "base_unit_measure", length = 3)
	public String getBaseUnitMeasure() {
		return this.baseUnitMeasure;
	}

	public void setBaseUnitMeasure(String baseUnitMeasure) {
		this.baseUnitMeasure = baseUnitMeasure;
	}

	@Column(name = "rounding_qty")
	public Integer getRoundingQty() {
		return this.roundingQty;
	}

	public void setRoundingQty(Integer roundingQty) {
		this.roundingQty = roundingQty;
	}

	@Column(name = "purchase_order_item", length = 6)
	public String getPurchaseOrderItem() {
		return this.purchaseOrderItem;
	}

	public void setPurchaseOrderItem(String purchaseOrderItem) {
		this.purchaseOrderItem = purchaseOrderItem;
	}

	@Column(name = "quantity_is_fixed", length = 1)
	public String getQuantityIsFixed() {
		return this.quantityIsFixed;
	}

	public void setQuantityIsFixed(String quantityIsFixed) {
		this.quantityIsFixed = quantityIsFixed;
	}

	@Column(name = "division", length = 2)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "business_area", length = 4)
	public String getBusinessArea() {
		return this.businessArea;
	}

	public void setBusinessArea(String businessArea) {
		this.businessArea = businessArea;
	}

	@Column(name = "net_value", precision = 15)
	public BigDecimal getNetValue() {
		return this.netValue;
	}

	public void setNetValue(BigDecimal netValue) {
		this.netValue = netValue;
	}

	@Column(name = "order_quantity")
	public Integer getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(Integer orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "gross_weight", precision = 15, scale = 3)
	public BigDecimal getGrossWeight() {
		return this.grossWeight;
	}

	public void setGrossWeight(BigDecimal grossWeight) {
		this.grossWeight = grossWeight;
	}

	@Column(name = "net_weight", precision = 15, scale = 3)
	public BigDecimal getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(BigDecimal netWeight) {
		this.netWeight = netWeight;
	}

	@Column(name = "weight_unit", length = 3)
	public String getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(String weightUnit) {
		this.weightUnit = weightUnit;
	}

	@Column(name = "volume", precision = 15, scale = 3)
	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	@Column(name = "delivery_priority", length = 2)
	public String getDeliveryPriority() {
		return this.deliveryPriority;
	}

	public void setDeliveryPriority(String deliveryPriority) {
		this.deliveryPriority = deliveryPriority;
	}

	@Column(name = "plant", length = 4)
	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	@Column(name = "storage_location", length = 4)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "shipping_point", length = 4)
	public String getShippingPoint() {
		return this.shippingPoint;
	}

	public void setShippingPoint(String shippingPoint) {
		this.shippingPoint = shippingPoint;
	}

	@Column(name = "receiving_point", length = 4)
	public String getReceivingPoint() {
		return this.receivingPoint;
	}

	public void setReceivingPoint(String receivingPoint) {
		this.receivingPoint = receivingPoint;
	}

	@Column(name = "route", length = 6)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 12)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "tax_classification", length = 20)
	public String getTaxClassification() {
		return this.taxClassification;
	}

	public void setTaxClassification(String taxClassification) {
		this.taxClassification = taxClassification;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "var_processing_time", length = 0)
	public Date getVarProcessingTime() {
		return this.varProcessingTime;
	}

	public void setVarProcessingTime(Date varProcessingTime) {
		this.varProcessingTime = varProcessingTime;
	}

	@Column(name = "returns", length = 1)
	public String getReturns() {
		return this.returns;
	}

	public void setReturns(String returns) {
		this.returns = returns;
	}

	@Column(name = "cash_discount", length = 1)
	public String getCashDiscount() {
		return this.cashDiscount;
	}

	public void setCashDiscount(String cashDiscount) {
		this.cashDiscount = cashDiscount;
	}

	@Column(name = "availability_check", length = 2)
	public String getAvailabilityCheck() {
		return this.availabilityCheck;
	}

	public void setAvailabilityCheck(String availabilityCheck) {
		this.availabilityCheck = availabilityCheck;
	}

	@Column(name = "volume_rebate_group", length = 2)
	public String getVolumeRebateGroup() {
		return this.volumeRebateGroup;
	}

	public void setVolumeRebateGroup(String volumeRebateGroup) {
		this.volumeRebateGroup = volumeRebateGroup;
	}

	@Column(name = "commission_group", length = 2)
	public String getCommissionGroup() {
		return this.commissionGroup;
	}

	public void setCommissionGroup(String commissionGroup) {
		this.commissionGroup = commissionGroup;
	}

	@Column(name = "ean_number", length = 13)
	public String getEanNumber() {
		return this.eanNumber;
	}

	public void setEanNumber(String eanNumber) {
		this.eanNumber = eanNumber;
	}

	@Column(name = "pricing", length = 1)
	public String getPricing() {
		return this.pricing;
	}

	public void setPricing(String pricing) {
		this.pricing = pricing;
	}

	@Column(name = "minimum_delivery_qty")
	public Integer getMinimumDeliveryQty() {
		return this.minimumDeliveryQty;
	}

	public void setMinimumDeliveryQty(Integer minimumDeliveryQty) {
		this.minimumDeliveryQty = minimumDeliveryQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_on", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "profit_center", length = 10)
	public String getProfitCenter() {
		return this.profitCenter;
	}

	public void setProfitCenter(String profitCenter) {
		this.profitCenter = profitCenter;
	}

	@Column(name = "credit_price", precision = 11)
	public BigDecimal getCreditPrice() {
		return this.creditPrice;
	}

	public void setCreditPrice(BigDecimal creditPrice) {
		this.creditPrice = creditPrice;
	}

	@Column(name = "partial_release", length = 1)
	public String getPartialRelease() {
		return this.partialRelease;
	}

	public void setPartialRelease(String partialRelease) {
		this.partialRelease = partialRelease;
	}

	@Column(name = "manual_price", length = 1)
	public String getManualPrice() {
		return this.manualPrice;
	}

	public void setManualPrice(String manualPrice) {
		this.manualPrice = manualPrice;
	}

	@Column(name = "Paymt_guarantee", length = 2)
	public String getPaymtGuarantee() {
		return this.paymtGuarantee;
	}

	public void setPaymtGuarantee(String paymtGuarantee) {
		this.paymtGuarantee = paymtGuarantee;
	}

	@Column(name = "guaranteed", length = 16)
	public String getGuaranteed() {
		return this.guaranteed;
	}

	public void setGuaranteed(String guaranteed) {
		this.guaranteed = guaranteed;
	}

	@Column(name = "cost_center", length = 10)
	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "modification_allowed", length = 1)
	public String getModificationAllowed() {
		return this.modificationAllowed;
	}

	public void setModificationAllowed(String modificationAllowed) {
		this.modificationAllowed = modificationAllowed;
	}

	@Column(name = "cancellation_allowed", length = 1)
	public String getCancellationAllowed() {
		return this.cancellationAllowed;
	}

	public void setCancellationAllowed(String cancellationAllowed) {
		this.cancellationAllowed = cancellationAllowed;
	}

}
