package com.udanti.sales.dao;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesHeader generated by hbm2java
 */
@Entity
@Table(name = "sales_header", catalog = "udnati")
public class SalesHeader implements java.io.Serializable {

	private int salesNumber;
	private String salesDocument;
	private Date createdOn;
	private Date time;
	private String createdBy;
	private Date quotationValidFrom;
	private Date quotationValidTo;
	private Date documentDate;
	private String salesDocumentType;
	private BigDecimal netValue;
	private String documentCurrency;
	private String salesOrganization;
	private String distributionChannel;
	private String division;
	private String salesGroup;
	private String salesOffice;
	private String businessArea;
	private Date validFromDate;
	private Date validToDate;
	private String docConditionNo;
	private Date requestedDelivDate;
	private Date propDate;
	private String completeDelivery;
	private String indicator;
	private String pricingProcedure;
	private String shippingConditions;
	private String billType;
	private String description;
	private String purchaseOrderNo;
	private String purchaseOrderType;
	private Date purchaseOrderDate;
	private String reference;
	private String name;
	private String telephone;
	private Date lastContactDate;
	private String soldToParty;
	private String costCenter;
	private Date changedOn;
	private String customerGroup;
	private String agreement;
	private String controllingArea;
	private String creditAccount;
	private String custCredGroup;
	private String riskCategory;
	private Date nextCheck;
	private String referenceDocument;
	private String checkPartnerAuth;
	private Date requestedDelyTime;
	private String businessUnit;
	private Date resolutionDate;
	private String modificationAllowed;
	private String cancellationAllowed;
	private String paymentMethods;
	private Set salesItems = new HashSet(0);

	public SalesHeader() {
	}

	public SalesHeader(int salesNumber) {
		this.salesNumber = salesNumber;
	}

	public SalesHeader(int salesNumber, String salesDocument, Date createdOn,
			Date time, String createdBy, Date quotationValidFrom,
			Date quotationValidTo, Date documentDate, String salesDocumentType,
			BigDecimal netValue, String documentCurrency,
			String salesOrganization, String distributionChannel,
			String division, String salesGroup, String salesOffice,
			String businessArea, Date validFromDate, Date validToDate,
			String docConditionNo, Date requestedDelivDate, Date propDate,
			String completeDelivery, String indicator, String pricingProcedure,
			String shippingConditions, String billType, String description,
			String purchaseOrderNo, String purchaseOrderType,
			Date purchaseOrderDate, String reference, String name,
			String telephone, Date lastContactDate, String soldToParty,
			String costCenter, Date changedOn, String customerGroup,
			String agreement, String controllingArea, String creditAccount,
			String custCredGroup, String riskCategory, Date nextCheck,
			String referenceDocument, String checkPartnerAuth,
			Date requestedDelyTime, String businessUnit, Date resolutionDate,
			String modificationAllowed, String cancellationAllowed,
			String paymentMethods, Set salesItems) {
		this.salesNumber = salesNumber;
		this.salesDocument = salesDocument;
		this.createdOn = createdOn;
		this.time = time;
		this.createdBy = createdBy;
		this.quotationValidFrom = quotationValidFrom;
		this.quotationValidTo = quotationValidTo;
		this.documentDate = documentDate;
		this.salesDocumentType = salesDocumentType;
		this.netValue = netValue;
		this.documentCurrency = documentCurrency;
		this.salesOrganization = salesOrganization;
		this.distributionChannel = distributionChannel;
		this.division = division;
		this.salesGroup = salesGroup;
		this.salesOffice = salesOffice;
		this.businessArea = businessArea;
		this.validFromDate = validFromDate;
		this.validToDate = validToDate;
		this.docConditionNo = docConditionNo;
		this.requestedDelivDate = requestedDelivDate;
		this.propDate = propDate;
		this.completeDelivery = completeDelivery;
		this.indicator = indicator;
		this.pricingProcedure = pricingProcedure;
		this.shippingConditions = shippingConditions;
		this.billType = billType;
		this.description = description;
		this.purchaseOrderNo = purchaseOrderNo;
		this.purchaseOrderType = purchaseOrderType;
		this.purchaseOrderDate = purchaseOrderDate;
		this.reference = reference;
		this.name = name;
		this.telephone = telephone;
		this.lastContactDate = lastContactDate;
		this.soldToParty = soldToParty;
		this.costCenter = costCenter;
		this.changedOn = changedOn;
		this.customerGroup = customerGroup;
		this.agreement = agreement;
		this.controllingArea = controllingArea;
		this.creditAccount = creditAccount;
		this.custCredGroup = custCredGroup;
		this.riskCategory = riskCategory;
		this.nextCheck = nextCheck;
		this.referenceDocument = referenceDocument;
		this.checkPartnerAuth = checkPartnerAuth;
		this.requestedDelyTime = requestedDelyTime;
		this.businessUnit = businessUnit;
		this.resolutionDate = resolutionDate;
		this.modificationAllowed = modificationAllowed;
		this.cancellationAllowed = cancellationAllowed;
		this.paymentMethods = paymentMethods;
		this.salesItems = salesItems;
	}

	@Id
	@Column(name = "sales_number", unique = true, nullable = false)
	public int getSalesNumber() {
		return this.salesNumber;
	}

	public void setSalesNumber(int salesNumber) {
		this.salesNumber = salesNumber;
	}

	@Column(name = "sales_document", length = 10)
	public String getSalesDocument() {
		return this.salesDocument;
	}

	public void setSalesDocument(String salesDocument) {
		this.salesDocument = salesDocument;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 0)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "created_by", length = 12)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quotation_valid_from", length = 0)
	public Date getQuotationValidFrom() {
		return this.quotationValidFrom;
	}

	public void setQuotationValidFrom(Date quotationValidFrom) {
		this.quotationValidFrom = quotationValidFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quotation_valid_to", length = 0)
	public Date getQuotationValidTo() {
		return this.quotationValidTo;
	}

	public void setQuotationValidTo(Date quotationValidTo) {
		this.quotationValidTo = quotationValidTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "document_date", length = 0)
	public Date getDocumentDate() {
		return this.documentDate;
	}

	public void setDocumentDate(Date documentDate) {
		this.documentDate = documentDate;
	}

	@Column(name = "sales_document_type", length = 4)
	public String getSalesDocumentType() {
		return this.salesDocumentType;
	}

	public void setSalesDocumentType(String salesDocumentType) {
		this.salesDocumentType = salesDocumentType;
	}

	@Column(name = "net_value", precision = 15)
	public BigDecimal getNetValue() {
		return this.netValue;
	}

	public void setNetValue(BigDecimal netValue) {
		this.netValue = netValue;
	}

	@Column(name = "document_currency", length = 5)
	public String getDocumentCurrency() {
		return this.documentCurrency;
	}

	public void setDocumentCurrency(String documentCurrency) {
		this.documentCurrency = documentCurrency;
	}

	@Column(name = "sales_organization", length = 4)
	public String getSalesOrganization() {
		return this.salesOrganization;
	}

	public void setSalesOrganization(String salesOrganization) {
		this.salesOrganization = salesOrganization;
	}

	@Column(name = "distribution_channel", length = 2)
	public String getDistributionChannel() {
		return this.distributionChannel;
	}

	public void setDistributionChannel(String distributionChannel) {
		this.distributionChannel = distributionChannel;
	}

	@Column(name = "division", length = 2)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "sales_group", length = 3)
	public String getSalesGroup() {
		return this.salesGroup;
	}

	public void setSalesGroup(String salesGroup) {
		this.salesGroup = salesGroup;
	}

	@Column(name = "sales_office", length = 4)
	public String getSalesOffice() {
		return this.salesOffice;
	}

	public void setSalesOffice(String salesOffice) {
		this.salesOffice = salesOffice;
	}

	@Column(name = "business_area", length = 4)
	public String getBusinessArea() {
		return this.businessArea;
	}

	public void setBusinessArea(String businessArea) {
		this.businessArea = businessArea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_from_date", length = 0)
	public Date getValidFromDate() {
		return this.validFromDate;
	}

	public void setValidFromDate(Date validFromDate) {
		this.validFromDate = validFromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_to_date", length = 0)
	public Date getValidToDate() {
		return this.validToDate;
	}

	public void setValidToDate(Date validToDate) {
		this.validToDate = validToDate;
	}

	@Column(name = "doc_condition_no", length = 10)
	public String getDocConditionNo() {
		return this.docConditionNo;
	}

	public void setDocConditionNo(String docConditionNo) {
		this.docConditionNo = docConditionNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "requested_deliv_date", length = 0)
	public Date getRequestedDelivDate() {
		return this.requestedDelivDate;
	}

	public void setRequestedDelivDate(Date requestedDelivDate) {
		this.requestedDelivDate = requestedDelivDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prop_date", length = 0)
	public Date getPropDate() {
		return this.propDate;
	}

	public void setPropDate(Date propDate) {
		this.propDate = propDate;
	}

	@Column(name = "complete_delivery", length = 1)
	public String getCompleteDelivery() {
		return this.completeDelivery;
	}

	public void setCompleteDelivery(String completeDelivery) {
		this.completeDelivery = completeDelivery;
	}

	@Column(name = "indicator", length = 1)
	public String getIndicator() {
		return this.indicator;
	}

	public void setIndicator(String indicator) {
		this.indicator = indicator;
	}

	@Column(name = "pricing_procedure", length = 6)
	public String getPricingProcedure() {
		return this.pricingProcedure;
	}

	public void setPricingProcedure(String pricingProcedure) {
		this.pricingProcedure = pricingProcedure;
	}

	@Column(name = "shipping_conditions", length = 2)
	public String getShippingConditions() {
		return this.shippingConditions;
	}

	public void setShippingConditions(String shippingConditions) {
		this.shippingConditions = shippingConditions;
	}

	@Column(name = "bill_type", length = 4)
	public String getBillType() {
		return this.billType;
	}

	public void setBillType(String billType) {
		this.billType = billType;
	}

	@Column(name = "description", length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "purchase_order_no", length = 20)
	public String getPurchaseOrderNo() {
		return this.purchaseOrderNo;
	}

	public void setPurchaseOrderNo(String purchaseOrderNo) {
		this.purchaseOrderNo = purchaseOrderNo;
	}

	@Column(name = "purchase_order_type", length = 4)
	public String getPurchaseOrderType() {
		return this.purchaseOrderType;
	}

	public void setPurchaseOrderType(String purchaseOrderType) {
		this.purchaseOrderType = purchaseOrderType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_order_date", length = 0)
	public Date getPurchaseOrderDate() {
		return this.purchaseOrderDate;
	}

	public void setPurchaseOrderDate(Date purchaseOrderDate) {
		this.purchaseOrderDate = purchaseOrderDate;
	}

	@Column(name = "reference", length = 12)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "name", length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "telephone", length = 16)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_contact_date", length = 0)
	public Date getLastContactDate() {
		return this.lastContactDate;
	}

	public void setLastContactDate(Date lastContactDate) {
		this.lastContactDate = lastContactDate;
	}

	@Column(name = "sold_to_party", length = 10)
	public String getSoldToParty() {
		return this.soldToParty;
	}

	public void setSoldToParty(String soldToParty) {
		this.soldToParty = soldToParty;
	}

	@Column(name = "cost_center", length = 10)
	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_on", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "customer_group", length = 3)
	public String getCustomerGroup() {
		return this.customerGroup;
	}

	public void setCustomerGroup(String customerGroup) {
		this.customerGroup = customerGroup;
	}

	@Column(name = "agreement", length = 10)
	public String getAgreement() {
		return this.agreement;
	}

	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}

	@Column(name = "controlling_area", length = 4)
	public String getControllingArea() {
		return this.controllingArea;
	}

	public void setControllingArea(String controllingArea) {
		this.controllingArea = controllingArea;
	}

	@Column(name = "credit_account", length = 10)
	public String getCreditAccount() {
		return this.creditAccount;
	}

	public void setCreditAccount(String creditAccount) {
		this.creditAccount = creditAccount;
	}

	@Column(name = "cust_cred_group", length = 4)
	public String getCustCredGroup() {
		return this.custCredGroup;
	}

	public void setCustCredGroup(String custCredGroup) {
		this.custCredGroup = custCredGroup;
	}

	@Column(name = "risk_category", length = 3)
	public String getRiskCategory() {
		return this.riskCategory;
	}

	public void setRiskCategory(String riskCategory) {
		this.riskCategory = riskCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "next_check", length = 0)
	public Date getNextCheck() {
		return this.nextCheck;
	}

	public void setNextCheck(Date nextCheck) {
		this.nextCheck = nextCheck;
	}

	@Column(name = "reference_document", length = 10)
	public String getReferenceDocument() {
		return this.referenceDocument;
	}

	public void setReferenceDocument(String referenceDocument) {
		this.referenceDocument = referenceDocument;
	}

	@Column(name = "check_partner_auth", length = 1)
	public String getCheckPartnerAuth() {
		return this.checkPartnerAuth;
	}

	public void setCheckPartnerAuth(String checkPartnerAuth) {
		this.checkPartnerAuth = checkPartnerAuth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "requested_dely_time", length = 0)
	public Date getRequestedDelyTime() {
		return this.requestedDelyTime;
	}

	public void setRequestedDelyTime(Date requestedDelyTime) {
		this.requestedDelyTime = requestedDelyTime;
	}

	@Column(name = "business_unit", length = 8)
	public String getBusinessUnit() {
		return this.businessUnit;
	}

	public void setBusinessUnit(String businessUnit) {
		this.businessUnit = businessUnit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "resolution_date", length = 0)
	public Date getResolutionDate() {
		return this.resolutionDate;
	}

	public void setResolutionDate(Date resolutionDate) {
		this.resolutionDate = resolutionDate;
	}

	@Column(name = "modification_allowed", length = 1)
	public String getModificationAllowed() {
		return this.modificationAllowed;
	}

	public void setModificationAllowed(String modificationAllowed) {
		this.modificationAllowed = modificationAllowed;
	}

	@Column(name = "cancellation_allowed", length = 1)
	public String getCancellationAllowed() {
		return this.cancellationAllowed;
	}

	public void setCancellationAllowed(String cancellationAllowed) {
		this.cancellationAllowed = cancellationAllowed;
	}

	@Column(name = "payment_methods", length = 10)
	public String getPaymentMethods() {
		return this.paymentMethods;
	}

	public void setPaymentMethods(String paymentMethods) {
		this.paymentMethods = paymentMethods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesHeader")
	public Set getSalesItems() {
		return this.salesItems;
	}

	public void setSalesItems(Set salesItems) {
		this.salesItems = salesItems;
	}

}
