// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillingHeader generated by hbm2java
 */
@Entity
@Table(name = "billing_header", catalog = "udnati")
public class BillingHeader implements java.io.Serializable {

	private int billingDocument;
	private String billingType;
	private String billingCategory;
	private Long currency;
	private String salesOrg;
	private String distributionCh;
	private String pricingPro;
	private String docConditionNo;
	private String shippingConditions;
	private Date billingDate;
	private String salesOrder;
	private Short fiscalYear;
	private Short postingPeriod;
	private String customerGroup;
	private String salesDistrict;
	private String priceList;
	private String postingStatus;
	private String destinationCountry;
	private String region;
	private String countyCode;
	private String cityCode;
	private String companyCode;
	private String taxClass1Cust;
	private Double netValue;
	private String createdBy;
	private Date time;
	private Date createdOn;
	private String payer;
	private String soldToParty;
	private String vatRegistrationNo;
	private Date changedOn;
	private String cancelledBillDoc;
	private String agreement;
	private String invoiceListType;
	private String division;
	private String creditAccount;
	private BigDecimal credDataExchRate;
	private String poNumber;
	private String agent;
	private Double taxAmount;
	private String taxType;
	private String paymentReference;
	private String paymentType;
	private Set billingItems = new HashSet(0);

	public BillingHeader() {
	}

	public BillingHeader(int billingDocument) {
		this.billingDocument = billingDocument;
	}

	public BillingHeader(int billingDocument, String billingType,
			String billingCategory, Long currency, String salesOrg,
			String distributionCh, String pricingPro, String docConditionNo,
			String shippingConditions, Date billingDate, String salesOrder,
			Short fiscalYear, Short postingPeriod, String customerGroup,
			String salesDistrict, String priceList, String postingStatus,
			String destinationCountry, String region, String countyCode,
			String cityCode, String companyCode, String taxClass1Cust,
			Double netValue, String createdBy, Date time, Date createdOn,
			String payer, String soldToParty, String vatRegistrationNo,
			Date changedOn, String cancelledBillDoc, String agreement,
			String invoiceListType, String division, String creditAccount,
			BigDecimal credDataExchRate, String poNumber, String agent,
			Double taxAmount, String taxType, String paymentReference,
			String paymentType, Set billingItems) {
		this.billingDocument = billingDocument;
		this.billingType = billingType;
		this.billingCategory = billingCategory;
		this.currency = currency;
		this.salesOrg = salesOrg;
		this.distributionCh = distributionCh;
		this.pricingPro = pricingPro;
		this.docConditionNo = docConditionNo;
		this.shippingConditions = shippingConditions;
		this.billingDate = billingDate;
		this.salesOrder = salesOrder;
		this.fiscalYear = fiscalYear;
		this.postingPeriod = postingPeriod;
		this.customerGroup = customerGroup;
		this.salesDistrict = salesDistrict;
		this.priceList = priceList;
		this.postingStatus = postingStatus;
		this.destinationCountry = destinationCountry;
		this.region = region;
		this.countyCode = countyCode;
		this.cityCode = cityCode;
		this.companyCode = companyCode;
		this.taxClass1Cust = taxClass1Cust;
		this.netValue = netValue;
		this.createdBy = createdBy;
		this.time = time;
		this.createdOn = createdOn;
		this.payer = payer;
		this.soldToParty = soldToParty;
		this.vatRegistrationNo = vatRegistrationNo;
		this.changedOn = changedOn;
		this.cancelledBillDoc = cancelledBillDoc;
		this.agreement = agreement;
		this.invoiceListType = invoiceListType;
		this.division = division;
		this.creditAccount = creditAccount;
		this.credDataExchRate = credDataExchRate;
		this.poNumber = poNumber;
		this.agent = agent;
		this.taxAmount = taxAmount;
		this.taxType = taxType;
		this.paymentReference = paymentReference;
		this.paymentType = paymentType;
		this.billingItems = billingItems;
	}

	@Id
	@Column(name = "billing_document", unique = true, nullable = false)
	public int getBillingDocument() {
		return this.billingDocument;
	}

	public void setBillingDocument(int billingDocument) {
		this.billingDocument = billingDocument;
	}

	@Column(name = "billing_type", length = 4)
	public String getBillingType() {
		return this.billingType;
	}

	public void setBillingType(String billingType) {
		this.billingType = billingType;
	}

	@Column(name = "billing_category", length = 4)
	public String getBillingCategory() {
		return this.billingCategory;
	}

	public void setBillingCategory(String billingCategory) {
		this.billingCategory = billingCategory;
	}

	@Column(name = "currency", precision = 10, scale = 0)
	public Long getCurrency() {
		return this.currency;
	}

	public void setCurrency(Long currency) {
		this.currency = currency;
	}

	@Column(name = "sales_org", length = 4)
	public String getSalesOrg() {
		return this.salesOrg;
	}

	public void setSalesOrg(String salesOrg) {
		this.salesOrg = salesOrg;
	}

	@Column(name = "distribution_ch", length = 2)
	public String getDistributionCh() {
		return this.distributionCh;
	}

	public void setDistributionCh(String distributionCh) {
		this.distributionCh = distributionCh;
	}

	@Column(name = "pricing_pro", length = 6)
	public String getPricingPro() {
		return this.pricingPro;
	}

	public void setPricingPro(String pricingPro) {
		this.pricingPro = pricingPro;
	}

	@Column(name = "doc_condition_no", length = 10)
	public String getDocConditionNo() {
		return this.docConditionNo;
	}

	public void setDocConditionNo(String docConditionNo) {
		this.docConditionNo = docConditionNo;
	}

	@Column(name = "shipping_conditions", length = 2)
	public String getShippingConditions() {
		return this.shippingConditions;
	}

	public void setShippingConditions(String shippingConditions) {
		this.shippingConditions = shippingConditions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "billing_date", length = 0)
	public Date getBillingDate() {
		return this.billingDate;
	}

	public void setBillingDate(Date billingDate) {
		this.billingDate = billingDate;
	}

	@Column(name = "sales_order", length = 10)
	public String getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(String salesOrder) {
		this.salesOrder = salesOrder;
	}

	@Column(name = "fiscal_year", precision = 4, scale = 0)
	public Short getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(Short fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "posting_period", precision = 3, scale = 0)
	public Short getPostingPeriod() {
		return this.postingPeriod;
	}

	public void setPostingPeriod(Short postingPeriod) {
		this.postingPeriod = postingPeriod;
	}

	@Column(name = "customer_group", length = 2)
	public String getCustomerGroup() {
		return this.customerGroup;
	}

	public void setCustomerGroup(String customerGroup) {
		this.customerGroup = customerGroup;
	}

	@Column(name = "sales_district", length = 6)
	public String getSalesDistrict() {
		return this.salesDistrict;
	}

	public void setSalesDistrict(String salesDistrict) {
		this.salesDistrict = salesDistrict;
	}

	@Column(name = "price_list", length = 2)
	public String getPriceList() {
		return this.priceList;
	}

	public void setPriceList(String priceList) {
		this.priceList = priceList;
	}

	@Column(name = "posting_status", length = 1)
	public String getPostingStatus() {
		return this.postingStatus;
	}

	public void setPostingStatus(String postingStatus) {
		this.postingStatus = postingStatus;
	}

	@Column(name = "destination_country", length = 3)
	public String getDestinationCountry() {
		return this.destinationCountry;
	}

	public void setDestinationCountry(String destinationCountry) {
		this.destinationCountry = destinationCountry;
	}

	@Column(name = "region", length = 3)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "county_code", length = 3)
	public String getCountyCode() {
		return this.countyCode;
	}

	public void setCountyCode(String countyCode) {
		this.countyCode = countyCode;
	}

	@Column(name = "city_code", length = 4)
	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	@Column(name = "company_code", length = 4)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "taxClass1_Cust", length = 1)
	public String getTaxClass1Cust() {
		return this.taxClass1Cust;
	}

	public void setTaxClass1Cust(String taxClass1Cust) {
		this.taxClass1Cust = taxClass1Cust;
	}

	@Column(name = "net_value", precision = 15)
	public Double getNetValue() {
		return this.netValue;
	}

	public void setNetValue(Double netValue) {
		this.netValue = netValue;
	}

	@Column(name = "created_by", length = 12)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 0)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "payer", length = 10)
	public String getPayer() {
		return this.payer;
	}

	public void setPayer(String payer) {
		this.payer = payer;
	}

	@Column(name = "sold_to_party", length = 10)
	public String getSoldToParty() {
		return this.soldToParty;
	}

	public void setSoldToParty(String soldToParty) {
		this.soldToParty = soldToParty;
	}

	@Column(name = "vat_registration_no", length = 20)
	public String getVatRegistrationNo() {
		return this.vatRegistrationNo;
	}

	public void setVatRegistrationNo(String vatRegistrationNo) {
		this.vatRegistrationNo = vatRegistrationNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "changed_on", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "cancelled_bill_doc", length = 10)
	public String getCancelledBillDoc() {
		return this.cancelledBillDoc;
	}

	public void setCancelledBillDoc(String cancelledBillDoc) {
		this.cancelledBillDoc = cancelledBillDoc;
	}

	@Column(name = "agreement", length = 10)
	public String getAgreement() {
		return this.agreement;
	}

	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}

	@Column(name = "invoice_list_type", length = 4)
	public String getInvoiceListType() {
		return this.invoiceListType;
	}

	public void setInvoiceListType(String invoiceListType) {
		this.invoiceListType = invoiceListType;
	}

	@Column(name = "division", length = 2)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "credit_account", length = 10)
	public String getCreditAccount() {
		return this.creditAccount;
	}

	public void setCreditAccount(String creditAccount) {
		this.creditAccount = creditAccount;
	}

	@Column(name = "cred_data_exch_rate", precision = 9, scale = 5)
	public BigDecimal getCredDataExchRate() {
		return this.credDataExchRate;
	}

	public void setCredDataExchRate(BigDecimal credDataExchRate) {
		this.credDataExchRate = credDataExchRate;
	}

	@Column(name = "po_number", length = 35)
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "agent", length = 6)
	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	@Column(name = "tax_amount", precision = 13)
	public Double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(Double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "tax_type", length = 2)
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "payment_reference", length = 30)
	public String getPaymentReference() {
		return this.paymentReference;
	}

	public void setPaymentReference(String paymentReference) {
		this.paymentReference = paymentReference;
	}

	@Column(name = "payment_type", length = 1)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "billingHeader")
	public Set getBillingItems() {
		return this.billingItems;
	}

	public void setBillingItems(Set billingItems) {
		this.billingItems = billingItems;
	}

}
