// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1

package com.udanti.delivery.dao;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveryItem generated by hbm2java
 */
@Entity
@Table(name = "delivery_item", catalog = "udnati")
public class DeliveryItem implements java.io.Serializable {

	private int deliveryItem;
	private DeliveryHeader deliveryHeader;
	private String category;
	private String column4;
	private String createdBy;
	private Date time;
	private Date createdOn;
	private String material;
	private String storageLocation;
	private String cartonNumber;
	private String quantity;
	private String salesUnit;
	private String netWeight;
	private String grossWeight;
	private String weightUnit;
	private String volume;
	private String voumeUnit;
	private String overWeight;
	private String actualQty;
	private String description;
	private String salesNumber;
	private String salesItem;
	private String billNumber;
	private String billItem;
	private String materialType;
	private String availabilityCheck;
	private String barcodeNumber;
	private Date fixedProcessTime;
	private Date varProcessTime;
	private Date changedOn;
	private String specialStock;
	private Double netPrice;
	private Double netValue;
	private String stockType;
	private String completed;
	private String alternatePrdoucer;

	public DeliveryItem() {
	}

	public DeliveryItem(int deliveryItem, DeliveryHeader deliveryHeader) {
		this.deliveryItem = deliveryItem;
		this.deliveryHeader = deliveryHeader;
	}

	public DeliveryItem(int deliveryItem, DeliveryHeader deliveryHeader,
			String category, String column4, String createdBy, Date time,
			Date createdOn, String material, String storageLocation,
			String cartonNumber, String quantity, String salesUnit,
			String netWeight, String grossWeight, String weightUnit,
			String volume, String voumeUnit, String overWeight,
			String actualQty, String description, String salesNumber,
			String salesItem, String billNumber, String billItem,
			String materialType, String availabilityCheck,
			String barcodeNumber, Date fixedProcessTime, Date varProcessTime,
			Date changedOn, String specialStock, Double netPrice,
			Double netValue, String stockType, String completed,
			String alternatePrdoucer) {
		this.deliveryItem = deliveryItem;
		this.deliveryHeader = deliveryHeader;
		this.category = category;
		this.column4 = column4;
		this.createdBy = createdBy;
		this.time = time;
		this.createdOn = createdOn;
		this.material = material;
		this.storageLocation = storageLocation;
		this.cartonNumber = cartonNumber;
		this.quantity = quantity;
		this.salesUnit = salesUnit;
		this.netWeight = netWeight;
		this.grossWeight = grossWeight;
		this.weightUnit = weightUnit;
		this.volume = volume;
		this.voumeUnit = voumeUnit;
		this.overWeight = overWeight;
		this.actualQty = actualQty;
		this.description = description;
		this.salesNumber = salesNumber;
		this.salesItem = salesItem;
		this.billNumber = billNumber;
		this.billItem = billItem;
		this.materialType = materialType;
		this.availabilityCheck = availabilityCheck;
		this.barcodeNumber = barcodeNumber;
		this.fixedProcessTime = fixedProcessTime;
		this.varProcessTime = varProcessTime;
		this.changedOn = changedOn;
		this.specialStock = specialStock;
		this.netPrice = netPrice;
		this.netValue = netValue;
		this.stockType = stockType;
		this.completed = completed;
		this.alternatePrdoucer = alternatePrdoucer;
	}

	@Id
	@Column(name = "delivery_item", unique = true, nullable = false)
	public int getDeliveryItem() {
		return this.deliveryItem;
	}

	public void setDeliveryItem(int deliveryItem) {
		this.deliveryItem = deliveryItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_number", nullable = false)
	public DeliveryHeader getDeliveryHeader() {
		return this.deliveryHeader;
	}

	public void setDeliveryHeader(DeliveryHeader deliveryHeader) {
		this.deliveryHeader = deliveryHeader;
	}

	@Column(name = "category", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "Column 4", length = 50)
	public String getColumn4() {
		return this.column4;
	}

	public void setColumn4(String column4) {
		this.column4 = column4;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Time", length = 0)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "material", length = 50)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "storage_location", length = 50)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "carton_number", length = 50)
	public String getCartonNumber() {
		return this.cartonNumber;
	}

	public void setCartonNumber(String cartonNumber) {
		this.cartonNumber = cartonNumber;
	}

	@Column(name = "quantity", length = 50)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Column(name = "sales_unit", length = 50)
	public String getSalesUnit() {
		return this.salesUnit;
	}

	public void setSalesUnit(String salesUnit) {
		this.salesUnit = salesUnit;
	}

	@Column(name = "net_weight", length = 50)
	public String getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(String netWeight) {
		this.netWeight = netWeight;
	}

	@Column(name = "gross_weight", length = 50)
	public String getGrossWeight() {
		return this.grossWeight;
	}

	public void setGrossWeight(String grossWeight) {
		this.grossWeight = grossWeight;
	}

	@Column(name = "weight_unit", length = 50)
	public String getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(String weightUnit) {
		this.weightUnit = weightUnit;
	}

	@Column(name = "volume", length = 50)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "voume_unit", length = 50)
	public String getVoumeUnit() {
		return this.voumeUnit;
	}

	public void setVoumeUnit(String voumeUnit) {
		this.voumeUnit = voumeUnit;
	}

	@Column(name = "over_weight", length = 50)
	public String getOverWeight() {
		return this.overWeight;
	}

	public void setOverWeight(String overWeight) {
		this.overWeight = overWeight;
	}

	@Column(name = "actual_qty", length = 50)
	public String getActualQty() {
		return this.actualQty;
	}

	public void setActualQty(String actualQty) {
		this.actualQty = actualQty;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sales_number", length = 50)
	public String getSalesNumber() {
		return this.salesNumber;
	}

	public void setSalesNumber(String salesNumber) {
		this.salesNumber = salesNumber;
	}

	@Column(name = "sales_item", length = 50)
	public String getSalesItem() {
		return this.salesItem;
	}

	public void setSalesItem(String salesItem) {
		this.salesItem = salesItem;
	}

	@Column(name = "bill_number", length = 50)
	public String getBillNumber() {
		return this.billNumber;
	}

	public void setBillNumber(String billNumber) {
		this.billNumber = billNumber;
	}

	@Column(name = "bill_item", length = 50)
	public String getBillItem() {
		return this.billItem;
	}

	public void setBillItem(String billItem) {
		this.billItem = billItem;
	}

	@Column(name = "material_type", length = 50)
	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	@Column(name = "availability_check", length = 50)
	public String getAvailabilityCheck() {
		return this.availabilityCheck;
	}

	public void setAvailabilityCheck(String availabilityCheck) {
		this.availabilityCheck = availabilityCheck;
	}

	@Column(name = "barcode_number", length = 50)
	public String getBarcodeNumber() {
		return this.barcodeNumber;
	}

	public void setBarcodeNumber(String barcodeNumber) {
		this.barcodeNumber = barcodeNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fixed_process_time", length = 0)
	public Date getFixedProcessTime() {
		return this.fixedProcessTime;
	}

	public void setFixedProcessTime(Date fixedProcessTime) {
		this.fixedProcessTime = fixedProcessTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "var_process_time", length = 0)
	public Date getVarProcessTime() {
		return this.varProcessTime;
	}

	public void setVarProcessTime(Date varProcessTime) {
		this.varProcessTime = varProcessTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_on", length = 0)
	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "special_stock", length = 50)
	public String getSpecialStock() {
		return this.specialStock;
	}

	public void setSpecialStock(String specialStock) {
		this.specialStock = specialStock;
	}

	@Column(name = "net_price", precision = 22, scale = 0)
	public Double getNetPrice() {
		return this.netPrice;
	}

	public void setNetPrice(Double netPrice) {
		this.netPrice = netPrice;
	}

	@Column(name = "net_value", precision = 22, scale = 0)
	public Double getNetValue() {
		return this.netValue;
	}

	public void setNetValue(Double netValue) {
		this.netValue = netValue;
	}

	@Column(name = "stock_type", length = 50)
	public String getStockType() {
		return this.stockType;
	}

	public void setStockType(String stockType) {
		this.stockType = stockType;
	}

	@Column(name = "completed", length = 50)
	public String getCompleted() {
		return this.completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}

	@Column(name = "alternate_prdoucer", length = 50)
	public String getAlternatePrdoucer() {
		return this.alternatePrdoucer;
	}

	public void setAlternatePrdoucer(String alternatePrdoucer) {
		this.alternatePrdoucer = alternatePrdoucer;
	}

}
