// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1
package com.udanti.common.dao;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.stereotype.Component;

/**
 * Customer generated by hbm2java
 */
@Component
@Entity
@Table(name = "customer", catalog = "udnati")
public class Customer implements java.io.Serializable {

	private int custId;
	private String country;
	private String name;
	private String prefferedName;
	private String city;
	private String postalCode;
	private String region;
	private String searchTerm;
	private String telephone;
	private String faxNumber;
	private String oneTimeAccnt;
	private String address;
	private String company;
	private String companyAddress;
	private String companyCity;
	private Date createdOn;
	private String createdBy;
	private String workingTimes;
	private String alternativePayer;
	private String accntGrp;
	private String customerGrp;
	private String vendor;
	private String taxRate;
	private String taxationGrp;
	private String transportation;
	private String zone;
	private String vatNum;
	private String defaultSoldToParty;
	private String annualSales;
	private String salesYear;
	private String employee;
	private String accnt;
	private String bankAccnt;
	private String companySize;
	private String defaulter;
	private String balanceType;
	private Double balance;

	public Customer() {
	}

	public Customer(int custId) {
		this.custId = custId;
	}

	public Customer(int custId, String country, String name,
			String prefferedName, String city, String postalCode,
			String region, String searchTerm, String telephone,
			String faxNumber, String oneTimeAccnt, String address,
			String company, String companyAddress, String companyCity,
			Date createdOn, String createdBy, String workingTimes,
			String alternativePayer, String accntGrp, String customerGrp,
			String vendor, String taxRate, String taxationGrp,
			String transportation, String zone, String vatNum,
			String defaultSoldToParty, String annualSales, String salesYear,
			String employee, String accnt, String bankAccnt,
			String companySize, String defaulter,String balanceType,Double balance) {
		this.custId = custId;
		this.country = country;
		this.name = name;
		this.prefferedName = prefferedName;
		this.city = city;
		this.postalCode = postalCode;
		this.region = region;
		this.searchTerm = searchTerm;
		this.telephone = telephone;
		this.faxNumber = faxNumber;
		this.oneTimeAccnt = oneTimeAccnt;
		this.address = address;
		this.company = company;
		this.companyAddress = companyAddress;
		this.companyCity = companyCity;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.workingTimes = workingTimes;
		this.alternativePayer = alternativePayer;
		this.accntGrp = accntGrp;
		this.customerGrp = customerGrp;
		this.vendor = vendor;
		this.taxRate = taxRate;
		this.taxationGrp = taxationGrp;
		this.transportation = transportation;
		this.zone = zone;
		this.vatNum = vatNum;
		this.defaultSoldToParty = defaultSoldToParty;
		this.annualSales = annualSales;
		this.salesYear = salesYear;
		this.employee = employee;
		this.accnt = accnt;
		this.bankAccnt = bankAccnt;
		this.companySize = companySize;
		this.defaulter = defaulter;
		this.balanceType = balanceType;
		this.balance = balance;
	}

	@Id
	@Column(name = "cust_id", unique = true, nullable = false)
	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "preffered_name", length = 50)
	public String getPrefferedName() {
		return this.prefferedName;
	}

	public void setPrefferedName(String prefferedName) {
		this.prefferedName = prefferedName;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postal_code", length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "region", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "search_term", length = 50)
	public String getSearchTerm() {
		return this.searchTerm;
	}

	public void setSearchTerm(String searchTerm) {
		this.searchTerm = searchTerm;
	}

	@Column(name = "telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax_number", length = 50)
	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	@Column(name = "one_time_accnt", length = 50)
	public String getOneTimeAccnt() {
		return this.oneTimeAccnt;
	}

	public void setOneTimeAccnt(String oneTimeAccnt) {
		this.oneTimeAccnt = oneTimeAccnt;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "company_address", length = 50)
	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	@Column(name = "company_city", length = 50)
	public String getCompanyCity() {
		return this.companyCity;
	}

	public void setCompanyCity(String companyCity) {
		this.companyCity = companyCity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "working_times", length = 50)
	public String getWorkingTimes() {
		return this.workingTimes;
	}

	public void setWorkingTimes(String workingTimes) {
		this.workingTimes = workingTimes;
	}

	@Column(name = "alternative_payer", length = 50)
	public String getAlternativePayer() {
		return this.alternativePayer;
	}

	public void setAlternativePayer(String alternativePayer) {
		this.alternativePayer = alternativePayer;
	}

	@Column(name = "accnt_grp", length = 50)
	public String getAccntGrp() {
		return this.accntGrp;
	}

	public void setAccntGrp(String accntGrp) {
		this.accntGrp = accntGrp;
	}

	@Column(name = "customer_grp", length = 50)
	public String getCustomerGrp() {
		return this.customerGrp;
	}

	public void setCustomerGrp(String customerGrp) {
		this.customerGrp = customerGrp;
	}

	@Column(name = "vendor", length = 50)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "TaxRate", length = 50)
	public String getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(String taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "Taxation_grp", length = 50)
	public String getTaxationGrp() {
		return this.taxationGrp;
	}

	public void setTaxationGrp(String taxationGrp) {
		this.taxationGrp = taxationGrp;
	}

	@Column(name = "transportation", length = 50)
	public String getTransportation() {
		return this.transportation;
	}

	public void setTransportation(String transportation) {
		this.transportation = transportation;
	}

	@Column(name = "zone", length = 50)
	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	@Column(name = "vat_num", length = 50)
	public String getVatNum() {
		return this.vatNum;
	}

	public void setVatNum(String vatNum) {
		this.vatNum = vatNum;
	}

	@Column(name = "default_sold_to_party", length = 50)
	public String getDefaultSoldToParty() {
		return this.defaultSoldToParty;
	}

	public void setDefaultSoldToParty(String defaultSoldToParty) {
		this.defaultSoldToParty = defaultSoldToParty;
	}

	@Column(name = "annual_sales", length = 50)
	public String getAnnualSales() {
		return this.annualSales;
	}

	public void setAnnualSales(String annualSales) {
		this.annualSales = annualSales;
	}

	@Column(name = "sales_year", length = 50)
	public String getSalesYear() {
		return this.salesYear;
	}

	public void setSalesYear(String salesYear) {
		this.salesYear = salesYear;
	}

	@Column(name = "employee", length = 50)
	public String getEmployee() {
		return this.employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}

	@Column(name = "Accnt", length = 50)
	public String getAccnt() {
		return this.accnt;
	}

	public void setAccnt(String accnt) {
		this.accnt = accnt;
	}

	@Column(name = "Bank_accnt", length = 50)
	public String getBankAccnt() {
		return this.bankAccnt;
	}

	public void setBankAccnt(String bankAccnt) {
		this.bankAccnt = bankAccnt;
	}

	@Column(name = "company_size", length = 50)
	public String getCompanySize() {
		return this.companySize;
	}

	public void setCompanySize(String companySize) {
		this.companySize = companySize;
	}

	@Column(name = "defaulter", length = 50)
	public String getDefaulter() {
		return this.defaulter;
	}

	public void setDefaulter(String defaulter) {
		this.defaulter = defaulter;
	}

	@Column(name = "balance_type", length = 10)
	public String getBalanceType() {
		return balanceType;
	}

	public void setBalanceType(String balanceType) {
		this.balanceType = balanceType;
	}
	@Column(name = "balance")
	public Double getBalance() {
		return balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

}
