// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShipmentItem generated by hbm2java
 */
@Entity
@Table(name = "shipment_item", catalog = "udnati")
public class ShipmentItem implements java.io.Serializable {

	private int shipmentItem;
	private ShipmentHeader shipmentHeader;
	private int deliveryNumber;
	private String createdBy;
	private Date createdOn;
	private Date time;

	public ShipmentItem() {
	}

	public ShipmentItem(int shipmentItem, ShipmentHeader shipmentHeader,
			int deliveryNumber, String createdBy) {
		this.shipmentItem = shipmentItem;
		this.shipmentHeader = shipmentHeader;
		this.deliveryNumber = deliveryNumber;
		this.createdBy = createdBy;
	}

	public ShipmentItem(int shipmentItem, ShipmentHeader shipmentHeader,
			int deliveryNumber, String createdBy, Date createdOn, Date time) {
		this.shipmentItem = shipmentItem;
		this.shipmentHeader = shipmentHeader;
		this.deliveryNumber = deliveryNumber;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.time = time;
	}

	@Id
	@Column(name = "shipment_item", unique = true, nullable = false)
	public int getShipmentItem() {
		return this.shipmentItem;
	}

	public void setShipmentItem(int shipmentItem) {
		this.shipmentItem = shipmentItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipment_number", nullable = false)
	public ShipmentHeader getShipmentHeader() {
		return this.shipmentHeader;
	}

	public void setShipmentHeader(ShipmentHeader shipmentHeader) {
		this.shipmentHeader = shipmentHeader;
	}

	@Column(name = "delivery_number", nullable = false)
	public int getDeliveryNumber() {
		return this.deliveryNumber;
	}

	public void setDeliveryNumber(int deliveryNumber) {
		this.deliveryNumber = deliveryNumber;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 0)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
