// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1

package com.udanti.shipment.dao;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShipmentHeader generated by hbm2java
 */
@Entity
@Table(name = "shipment_header", catalog = "udnati")
public class ShipmentHeader implements java.io.Serializable {

	private int shipmentNumber;
	private String category;
	private String shipmentType;
	private String createdBy;
	private Date createdOn;
	private Date time;
	private String changedBy;
	private String changedOn;
	private String shippingCond;
	private String shipmentRoute;
	private String containerId;
	private Date plannedDate;
	private Date plannedEnd;
	private Date actualStart;
	private Date actualEnd;
	private String shimpmentCompletion;
	private String transportStatus;
	private String serviceAgent;
	private String salesOrder;
	private Integer handlingUnits;
	private String weightUnit;
	private String volumeUnit;
	private Integer distance;
	private Double travelTime;
	private Double shipmentCost;
	private Double totalCost;
	private String handle;
	private String freightId;
	private String driverName;
	private String vehicleNumber;
	private String driverContact;
	private Set<ShipmentItem> shipmentItems = new HashSet<ShipmentItem>(0);

	public ShipmentHeader() {
	}

	public ShipmentHeader(int shipmentNumber) {
		this.shipmentNumber = shipmentNumber;
	}

	public ShipmentHeader(int shipmentNumber, String category,
			String shipmentType, String createdBy, Date createdOn, Date time,
			String changedBy, String changedOn, String shippingCond,
			String shipmentRoute, String containerId, Date plannedDate,
			Date plannedEnd, Date actualStart, Date actualEnd,
			String shimpmentCompletion, String transportStatus,
			String serviceAgent, String salesOrder, Integer handlingUnits,
			String weightUnit, String volumeUnit, Integer distance,
			Double travelTime, Double shipmentCost, Double totalCost,
			String handle, String freightId, String driverName,
			String vehicleNumber, String driverContact, Set<ShipmentItem> shipmentItems) {
		this.shipmentNumber = shipmentNumber;
		this.category = category;
		this.shipmentType = shipmentType;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.time = time;
		this.changedBy = changedBy;
		this.changedOn = changedOn;
		this.shippingCond = shippingCond;
		this.shipmentRoute = shipmentRoute;
		this.containerId = containerId;
		this.plannedDate = plannedDate;
		this.plannedEnd = plannedEnd;
		this.actualStart = actualStart;
		this.actualEnd = actualEnd;
		this.shimpmentCompletion = shimpmentCompletion;
		this.transportStatus = transportStatus;
		this.serviceAgent = serviceAgent;
		this.salesOrder = salesOrder;
		this.handlingUnits = handlingUnits;
		this.weightUnit = weightUnit;
		this.volumeUnit = volumeUnit;
		this.distance = distance;
		this.travelTime = travelTime;
		this.shipmentCost = shipmentCost;
		this.totalCost = totalCost;
		this.handle = handle;
		this.freightId = freightId;
		this.driverName = driverName;
		this.vehicleNumber = vehicleNumber;
		this.driverContact = driverContact;
		this.shipmentItems = shipmentItems;
	}

	@Id
	@Column(name = "shipment_number", unique = true, nullable = false)
	public int getShipmentNumber() {
		return this.shipmentNumber;
	}

	public void setShipmentNumber(int shipmentNumber) {
		this.shipmentNumber = shipmentNumber;
	}

	@Column(name = "category", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "shipment_type", length = 50)
	public String getShipmentType() {
		return this.shipmentType;
	}

	public void setShipmentType(String shipmentType) {
		this.shipmentType = shipmentType;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Time", length = 0)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "changed_by", length = 50)
	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	@Column(name = "changed_on", length = 50)
	public String getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(String changedOn) {
		this.changedOn = changedOn;
	}

	@Column(name = "shipping_cond", length = 50)
	public String getShippingCond() {
		return this.shippingCond;
	}

	public void setShippingCond(String shippingCond) {
		this.shippingCond = shippingCond;
	}

	@Column(name = "shipment_route", length = 50)
	public String getShipmentRoute() {
		return this.shipmentRoute;
	}

	public void setShipmentRoute(String shipmentRoute) {
		this.shipmentRoute = shipmentRoute;
	}

	@Column(name = "container_id", length = 50)
	public String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "planned_date", length = 0)
	public Date getPlannedDate() {
		return this.plannedDate;
	}

	public void setPlannedDate(Date plannedDate) {
		this.plannedDate = plannedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "planned_end", length = 0)
	public Date getPlannedEnd() {
		return this.plannedEnd;
	}

	public void setPlannedEnd(Date plannedEnd) {
		this.plannedEnd = plannedEnd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actual_start", length = 0)
	public Date getActualStart() {
		return this.actualStart;
	}

	public void setActualStart(Date actualStart) {
		this.actualStart = actualStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actual_end", length = 0)
	public Date getActualEnd() {
		return this.actualEnd;
	}

	public void setActualEnd(Date actualEnd) {
		this.actualEnd = actualEnd;
	}

	@Column(name = "shimpment_completion", length = 50)
	public String getShimpmentCompletion() {
		return this.shimpmentCompletion;
	}

	public void setShimpmentCompletion(String shimpmentCompletion) {
		this.shimpmentCompletion = shimpmentCompletion;
	}

	@Column(name = "transport_status", length = 50)
	public String getTransportStatus() {
		return this.transportStatus;
	}

	public void setTransportStatus(String transportStatus) {
		this.transportStatus = transportStatus;
	}

	@Column(name = "service_agent", length = 50)
	public String getServiceAgent() {
		return this.serviceAgent;
	}

	public void setServiceAgent(String serviceAgent) {
		this.serviceAgent = serviceAgent;
	}

	@Column(name = "sales_order", length = 50)
	public String getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(String salesOrder) {
		this.salesOrder = salesOrder;
	}

	@Column(name = "handling_units")
	public Integer getHandlingUnits() {
		return this.handlingUnits;
	}

	public void setHandlingUnits(Integer handlingUnits) {
		this.handlingUnits = handlingUnits;
	}

	@Column(name = "weight_unit", length = 50)
	public String getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(String weightUnit) {
		this.weightUnit = weightUnit;
	}

	@Column(name = "volume_unit", length = 50)
	public String getVolumeUnit() {
		return this.volumeUnit;
	}

	public void setVolumeUnit(String volumeUnit) {
		this.volumeUnit = volumeUnit;
	}

	@Column(name = "distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	@Column(name = "travel_time", precision = 22, scale = 0)
	public Double getTravelTime() {
		return this.travelTime;
	}

	public void setTravelTime(Double travelTime) {
		this.travelTime = travelTime;
	}

	@Column(name = "shipment_cost", precision = 22, scale = 0)
	public Double getShipmentCost() {
		return this.shipmentCost;
	}

	public void setShipmentCost(Double shipmentCost) {
		this.shipmentCost = shipmentCost;
	}

	@Column(name = "total_cost", precision = 22, scale = 0)
	public Double getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(Double totalCost) {
		this.totalCost = totalCost;
	}

	@Column(name = "handle", length = 50)
	public String getHandle() {
		return this.handle;
	}

	public void setHandle(String handle) {
		this.handle = handle;
	}

	@Column(name = "freight_id", length = 50)
	public String getFreightId() {
		return this.freightId;
	}

	public void setFreightId(String freightId) {
		this.freightId = freightId;
	}

	@Column(name = "driver_name", length = 50)
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "vehicle_number", length = 50)
	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	@Column(name = "driver_contact", length = 50)
	public String getDriverContact() {
		return this.driverContact;
	}

	public void setDriverContact(String driverContact) {
		this.driverContact = driverContact;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shipmentHeader")
	public Set<ShipmentItem> getShipmentItems() {
		return this.shipmentItems;
	}

	public void setShipmentItems(Set<ShipmentItem> shipmentItems) {
		this.shipmentItems = shipmentItems;
	}

}
