// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseItem generated by hbm2java
 */
@Entity
@Table(name = "purchase_item", catalog = "udnati")
public class PurchaseItem implements java.io.Serializable {

	private int purchaseItemId;
	private String purchasingDocument;
	private String item;
	private String lastChangedOn;
	private String material;
	private String storageLocation;
	private String materialGroup;
	private String purchasingInfoRec;
	private String targetQuantity;
	private String orderQuantity;
	private String orderUnit;
	private String price;
	private String netOrderValue;
	private String grossOrderValue;
	private String grProcessingTime;
	private String taxCode;
	private String printPrice;
	private String estimatedPrice;
	private String itemCategory;
	private String goodsReceipt;
	private String invoiceReceipt;
	private String grBasedInvVerif;
	private String shippingInstr;
	private Date priceDate;
	private String purchDocCategory;
	private String effectivValue;
	private String conditionGroup;
	private String noCashDiscount;
	private String plannedDelivTime;
	private String netWeight;
	private String unitOfWeight;
	private String taxJurisdiction;
	private String specialStock;
	private String barcode;
	private String fundsCenter;
	private String advanceProcurement;
	private String priorVendor;
	private String shippingType;
	private Date dateOfLastTransmittedChange;
	private String timeOfTransmission;
	private String nextTransmissionNumber;
	private String matLedgerActive;
	private String returnsItem;
	private String reasonForOrdering;
	private String inflationIndex;
	private String manufacturer;

	public PurchaseItem() {
	}

	public PurchaseItem(int purchaseItemId) {
		this.purchaseItemId = purchaseItemId;
	}

	public PurchaseItem(int purchaseItemId, String purchasingDocument,
			String item, String lastChangedOn, String material,
			String storageLocation, String materialGroup,
			String purchasingInfoRec, String targetQuantity,
			String orderQuantity, String orderUnit, String price,
			String netOrderValue, String grossOrderValue,
			String grProcessingTime, String taxCode, String printPrice,
			String estimatedPrice, String itemCategory, String goodsReceipt,
			String invoiceReceipt, String grBasedInvVerif,
			String shippingInstr, Date priceDate, String purchDocCategory,
			String effectivValue, String conditionGroup, String noCashDiscount,
			String plannedDelivTime, String netWeight, String unitOfWeight,
			String taxJurisdiction, String specialStock, String barcode,
			String fundsCenter, String advanceProcurement, String priorVendor,
			String shippingType, Date dateOfLastTransmittedChange,
			String timeOfTransmission, String nextTransmissionNumber,
			String matLedgerActive, String returnsItem,
			String reasonForOrdering, String inflationIndex, String manufacturer) {
		this.purchaseItemId = purchaseItemId;
		this.purchasingDocument = purchasingDocument;
		this.item = item;
		this.lastChangedOn = lastChangedOn;
		this.material = material;
		this.storageLocation = storageLocation;
		this.materialGroup = materialGroup;
		this.purchasingInfoRec = purchasingInfoRec;
		this.targetQuantity = targetQuantity;
		this.orderQuantity = orderQuantity;
		this.orderUnit = orderUnit;
		this.price = price;
		this.netOrderValue = netOrderValue;
		this.grossOrderValue = grossOrderValue;
		this.grProcessingTime = grProcessingTime;
		this.taxCode = taxCode;
		this.printPrice = printPrice;
		this.estimatedPrice = estimatedPrice;
		this.itemCategory = itemCategory;
		this.goodsReceipt = goodsReceipt;
		this.invoiceReceipt = invoiceReceipt;
		this.grBasedInvVerif = grBasedInvVerif;
		this.shippingInstr = shippingInstr;
		this.priceDate = priceDate;
		this.purchDocCategory = purchDocCategory;
		this.effectivValue = effectivValue;
		this.conditionGroup = conditionGroup;
		this.noCashDiscount = noCashDiscount;
		this.plannedDelivTime = plannedDelivTime;
		this.netWeight = netWeight;
		this.unitOfWeight = unitOfWeight;
		this.taxJurisdiction = taxJurisdiction;
		this.specialStock = specialStock;
		this.barcode = barcode;
		this.fundsCenter = fundsCenter;
		this.advanceProcurement = advanceProcurement;
		this.priorVendor = priorVendor;
		this.shippingType = shippingType;
		this.dateOfLastTransmittedChange = dateOfLastTransmittedChange;
		this.timeOfTransmission = timeOfTransmission;
		this.nextTransmissionNumber = nextTransmissionNumber;
		this.matLedgerActive = matLedgerActive;
		this.returnsItem = returnsItem;
		this.reasonForOrdering = reasonForOrdering;
		this.inflationIndex = inflationIndex;
		this.manufacturer = manufacturer;
	}

	@Id
	@Column(name = "purchase_item_id", unique = true, nullable = false)
	public int getPurchaseItemId() {
		return this.purchaseItemId;
	}

	public void setPurchaseItemId(int purchaseItemId) {
		this.purchaseItemId = purchaseItemId;
	}

	@Column(name = "purchasing_document", length = 50)
	public String getPurchasingDocument() {
		return this.purchasingDocument;
	}

	public void setPurchasingDocument(String purchasingDocument) {
		this.purchasingDocument = purchasingDocument;
	}

	@Column(name = "item", length = 50)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "last_changed_on", length = 50)
	public String getLastChangedOn() {
		return this.lastChangedOn;
	}

	public void setLastChangedOn(String lastChangedOn) {
		this.lastChangedOn = lastChangedOn;
	}

	@Column(name = "material", length = 50)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "storage_location", length = 50)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "material_group", length = 50)
	public String getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}

	@Column(name = "purchasing_info_rec", length = 50)
	public String getPurchasingInfoRec() {
		return this.purchasingInfoRec;
	}

	public void setPurchasingInfoRec(String purchasingInfoRec) {
		this.purchasingInfoRec = purchasingInfoRec;
	}

	@Column(name = "target_quantity", length = 50)
	public String getTargetQuantity() {
		return this.targetQuantity;
	}

	public void setTargetQuantity(String targetQuantity) {
		this.targetQuantity = targetQuantity;
	}

	@Column(name = "order_quantity", length = 50)
	public String getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(String orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "order_unit", length = 50)
	public String getOrderUnit() {
		return this.orderUnit;
	}

	public void setOrderUnit(String orderUnit) {
		this.orderUnit = orderUnit;
	}

	@Column(name = "price", length = 50)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "net_order_value", length = 50)
	public String getNetOrderValue() {
		return this.netOrderValue;
	}

	public void setNetOrderValue(String netOrderValue) {
		this.netOrderValue = netOrderValue;
	}

	@Column(name = "gross_order_value", length = 50)
	public String getGrossOrderValue() {
		return this.grossOrderValue;
	}

	public void setGrossOrderValue(String grossOrderValue) {
		this.grossOrderValue = grossOrderValue;
	}

	@Column(name = "gr_processing_time", length = 50)
	public String getGrProcessingTime() {
		return this.grProcessingTime;
	}

	public void setGrProcessingTime(String grProcessingTime) {
		this.grProcessingTime = grProcessingTime;
	}

	@Column(name = "tax_code", length = 50)
	public String getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "print_price", length = 50)
	public String getPrintPrice() {
		return this.printPrice;
	}

	public void setPrintPrice(String printPrice) {
		this.printPrice = printPrice;
	}

	@Column(name = "estimated_price", length = 50)
	public String getEstimatedPrice() {
		return this.estimatedPrice;
	}

	public void setEstimatedPrice(String estimatedPrice) {
		this.estimatedPrice = estimatedPrice;
	}

	@Column(name = "item_category", length = 50)
	public String getItemCategory() {
		return this.itemCategory;
	}

	public void setItemCategory(String itemCategory) {
		this.itemCategory = itemCategory;
	}

	@Column(name = "goods_receipt", length = 50)
	public String getGoodsReceipt() {
		return this.goodsReceipt;
	}

	public void setGoodsReceipt(String goodsReceipt) {
		this.goodsReceipt = goodsReceipt;
	}

	@Column(name = "invoice_receipt", length = 50)
	public String getInvoiceReceipt() {
		return this.invoiceReceipt;
	}

	public void setInvoiceReceipt(String invoiceReceipt) {
		this.invoiceReceipt = invoiceReceipt;
	}

	@Column(name = "gr_based_inv_verif", length = 50)
	public String getGrBasedInvVerif() {
		return this.grBasedInvVerif;
	}

	public void setGrBasedInvVerif(String grBasedInvVerif) {
		this.grBasedInvVerif = grBasedInvVerif;
	}

	@Column(name = "shipping_instr", length = 50)
	public String getShippingInstr() {
		return this.shippingInstr;
	}

	public void setShippingInstr(String shippingInstr) {
		this.shippingInstr = shippingInstr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "price_date", length = 0)
	public Date getPriceDate() {
		return this.priceDate;
	}

	public void setPriceDate(Date priceDate) {
		this.priceDate = priceDate;
	}

	@Column(name = "purch_doc_category", length = 50)
	public String getPurchDocCategory() {
		return this.purchDocCategory;
	}

	public void setPurchDocCategory(String purchDocCategory) {
		this.purchDocCategory = purchDocCategory;
	}

	@Column(name = "effectiv_value", length = 50)
	public String getEffectivValue() {
		return this.effectivValue;
	}

	public void setEffectivValue(String effectivValue) {
		this.effectivValue = effectivValue;
	}

	@Column(name = "condition_group", length = 50)
	public String getConditionGroup() {
		return this.conditionGroup;
	}

	public void setConditionGroup(String conditionGroup) {
		this.conditionGroup = conditionGroup;
	}

	@Column(name = "no_cash_discount", length = 50)
	public String getNoCashDiscount() {
		return this.noCashDiscount;
	}

	public void setNoCashDiscount(String noCashDiscount) {
		this.noCashDiscount = noCashDiscount;
	}

	@Column(name = "planned_deliv_time", length = 50)
	public String getPlannedDelivTime() {
		return this.plannedDelivTime;
	}

	public void setPlannedDelivTime(String plannedDelivTime) {
		this.plannedDelivTime = plannedDelivTime;
	}

	@Column(name = "net_weight", length = 50)
	public String getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(String netWeight) {
		this.netWeight = netWeight;
	}

	@Column(name = "unit_of_weight", length = 50)
	public String getUnitOfWeight() {
		return this.unitOfWeight;
	}

	public void setUnitOfWeight(String unitOfWeight) {
		this.unitOfWeight = unitOfWeight;
	}

	@Column(name = "tax_jurisdiction", length = 50)
	public String getTaxJurisdiction() {
		return this.taxJurisdiction;
	}

	public void setTaxJurisdiction(String taxJurisdiction) {
		this.taxJurisdiction = taxJurisdiction;
	}

	@Column(name = "special_stock", length = 50)
	public String getSpecialStock() {
		return this.specialStock;
	}

	public void setSpecialStock(String specialStock) {
		this.specialStock = specialStock;
	}

	@Column(name = "barcode", length = 50)
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@Column(name = "funds_center", length = 50)
	public String getFundsCenter() {
		return this.fundsCenter;
	}

	public void setFundsCenter(String fundsCenter) {
		this.fundsCenter = fundsCenter;
	}

	@Column(name = "advance_procurement", length = 50)
	public String getAdvanceProcurement() {
		return this.advanceProcurement;
	}

	public void setAdvanceProcurement(String advanceProcurement) {
		this.advanceProcurement = advanceProcurement;
	}

	@Column(name = "prior_vendor", length = 50)
	public String getPriorVendor() {
		return this.priorVendor;
	}

	public void setPriorVendor(String priorVendor) {
		this.priorVendor = priorVendor;
	}

	@Column(name = "shipping_type", length = 50)
	public String getShippingType() {
		return this.shippingType;
	}

	public void setShippingType(String shippingType) {
		this.shippingType = shippingType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_last_transmitted_change", length = 0)
	public Date getDateOfLastTransmittedChange() {
		return this.dateOfLastTransmittedChange;
	}

	public void setDateOfLastTransmittedChange(Date dateOfLastTransmittedChange) {
		this.dateOfLastTransmittedChange = dateOfLastTransmittedChange;
	}

	@Column(name = "time_of_transmission", length = 50)
	public String getTimeOfTransmission() {
		return this.timeOfTransmission;
	}

	public void setTimeOfTransmission(String timeOfTransmission) {
		this.timeOfTransmission = timeOfTransmission;
	}

	@Column(name = "next_transmission_number", length = 50)
	public String getNextTransmissionNumber() {
		return this.nextTransmissionNumber;
	}

	public void setNextTransmissionNumber(String nextTransmissionNumber) {
		this.nextTransmissionNumber = nextTransmissionNumber;
	}

	@Column(name = "mat_ledger_active", length = 50)
	public String getMatLedgerActive() {
		return this.matLedgerActive;
	}

	public void setMatLedgerActive(String matLedgerActive) {
		this.matLedgerActive = matLedgerActive;
	}

	@Column(name = "returns_item", length = 50)
	public String getReturnsItem() {
		return this.returnsItem;
	}

	public void setReturnsItem(String returnsItem) {
		this.returnsItem = returnsItem;
	}

	@Column(name = "reason_for_ordering", length = 50)
	public String getReasonForOrdering() {
		return this.reasonForOrdering;
	}

	public void setReasonForOrdering(String reasonForOrdering) {
		this.reasonForOrdering = reasonForOrdering;
	}

	@Column(name = "inflation_index", length = 50)
	public String getInflationIndex() {
		return this.inflationIndex;
	}

	public void setInflationIndex(String inflationIndex) {
		this.inflationIndex = inflationIndex;
	}

	@Column(name = "manufacturer", length = 50)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

}
