// default package
// Generated 12 Jul, 2015 1:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseHeader generated by hbm2java
 */
@Entity
@Table(name = "purchase_header", catalog = "udnati")
public class PurchaseHeader implements java.io.Serializable {

	private int purcahseHdId;
	private String purchasingDocument;
	private String companyCode;
	private String purchDocCategory;
	private String purchasingDocType;
	private String status;
	private Date createdOn;
	private String createdBy;
	private String purchOrganization;
	private String currency;
	private Date documentDate;
	private String validityPerStart;
	private String validityPeriodEnd;
	private String quotationDeadline;
	private String warranty;
	private String bidInvitation;
	private String quotation;
	private String quotationDate;
	private String yourReference;
	private String salesperson;
	private String telephone;
	private String supplyingVendor;
	private String customer;
	private String completeDelivery;
	private String grMessage;
	private String targetValHeader;
	private String invoicingParty;
	private String addressNumber;
	private String countrySlsTaxNo;
	private String vatRegistrationNo;
	private String reasonForCanc;
	private String documentNumber;
	private String incomplete;
	private String downPayment;
	private String downPaytPercentage;
	private String downPaymentAmount;
	private String dueDateForDownPayment;
	private String shippingType;
	private String handoverLocation;
	private String shippingConditions;

	public PurchaseHeader() {
	}

	public PurchaseHeader(int purcahseHdId) {
		this.purcahseHdId = purcahseHdId;
	}

	public PurchaseHeader(int purcahseHdId, String purchasingDocument,
			String companyCode, String purchDocCategory,
			String purchasingDocType, String status, Date createdOn,
			String createdBy, String purchOrganization, String currency,
			Date documentDate, String validityPerStart,
			String validityPeriodEnd, String quotationDeadline,
			String warranty, String bidInvitation, String quotation,
			String quotationDate, String yourReference, String salesperson,
			String telephone, String supplyingVendor, String customer,
			String completeDelivery, String grMessage, String targetValHeader,
			String invoicingParty, String addressNumber,
			String countrySlsTaxNo, String vatRegistrationNo,
			String reasonForCanc, String documentNumber, String incomplete,
			String downPayment, String downPaytPercentage,
			String downPaymentAmount, String dueDateForDownPayment,
			String shippingType, String handoverLocation,
			String shippingConditions) {
		this.purcahseHdId = purcahseHdId;
		this.purchasingDocument = purchasingDocument;
		this.companyCode = companyCode;
		this.purchDocCategory = purchDocCategory;
		this.purchasingDocType = purchasingDocType;
		this.status = status;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.purchOrganization = purchOrganization;
		this.currency = currency;
		this.documentDate = documentDate;
		this.validityPerStart = validityPerStart;
		this.validityPeriodEnd = validityPeriodEnd;
		this.quotationDeadline = quotationDeadline;
		this.warranty = warranty;
		this.bidInvitation = bidInvitation;
		this.quotation = quotation;
		this.quotationDate = quotationDate;
		this.yourReference = yourReference;
		this.salesperson = salesperson;
		this.telephone = telephone;
		this.supplyingVendor = supplyingVendor;
		this.customer = customer;
		this.completeDelivery = completeDelivery;
		this.grMessage = grMessage;
		this.targetValHeader = targetValHeader;
		this.invoicingParty = invoicingParty;
		this.addressNumber = addressNumber;
		this.countrySlsTaxNo = countrySlsTaxNo;
		this.vatRegistrationNo = vatRegistrationNo;
		this.reasonForCanc = reasonForCanc;
		this.documentNumber = documentNumber;
		this.incomplete = incomplete;
		this.downPayment = downPayment;
		this.downPaytPercentage = downPaytPercentage;
		this.downPaymentAmount = downPaymentAmount;
		this.dueDateForDownPayment = dueDateForDownPayment;
		this.shippingType = shippingType;
		this.handoverLocation = handoverLocation;
		this.shippingConditions = shippingConditions;
	}

	@Id
	@Column(name = "purcahse_hd_id", unique = true, nullable = false)
	public int getPurcahseHdId() {
		return this.purcahseHdId;
	}

	public void setPurcahseHdId(int purcahseHdId) {
		this.purcahseHdId = purcahseHdId;
	}

	@Column(name = "purchasing_document", length = 50)
	public String getPurchasingDocument() {
		return this.purchasingDocument;
	}

	public void setPurchasingDocument(String purchasingDocument) {
		this.purchasingDocument = purchasingDocument;
	}

	@Column(name = "company_code", length = 50)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "purch_Doc_Category", length = 50)
	public String getPurchDocCategory() {
		return this.purchDocCategory;
	}

	public void setPurchDocCategory(String purchDocCategory) {
		this.purchDocCategory = purchDocCategory;
	}

	@Column(name = "purchasing_doc_type", length = 50)
	public String getPurchasingDocType() {
		return this.purchasingDocType;
	}

	public void setPurchasingDocType(String purchasingDocType) {
		this.purchasingDocType = purchasingDocType;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "purch_organization", length = 50)
	public String getPurchOrganization() {
		return this.purchOrganization;
	}

	public void setPurchOrganization(String purchOrganization) {
		this.purchOrganization = purchOrganization;
	}

	@Column(name = "currency", length = 50)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "document_date", length = 0)
	public Date getDocumentDate() {
		return this.documentDate;
	}

	public void setDocumentDate(Date documentDate) {
		this.documentDate = documentDate;
	}

	@Column(name = "validity_per_start", length = 50)
	public String getValidityPerStart() {
		return this.validityPerStart;
	}

	public void setValidityPerStart(String validityPerStart) {
		this.validityPerStart = validityPerStart;
	}

	@Column(name = "validity_period_end", length = 50)
	public String getValidityPeriodEnd() {
		return this.validityPeriodEnd;
	}

	public void setValidityPeriodEnd(String validityPeriodEnd) {
		this.validityPeriodEnd = validityPeriodEnd;
	}

	@Column(name = "quotation_deadline", length = 50)
	public String getQuotationDeadline() {
		return this.quotationDeadline;
	}

	public void setQuotationDeadline(String quotationDeadline) {
		this.quotationDeadline = quotationDeadline;
	}

	@Column(name = "warranty", length = 50)
	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	@Column(name = "bid_invitation", length = 50)
	public String getBidInvitation() {
		return this.bidInvitation;
	}

	public void setBidInvitation(String bidInvitation) {
		this.bidInvitation = bidInvitation;
	}

	@Column(name = "quotation", length = 50)
	public String getQuotation() {
		return this.quotation;
	}

	public void setQuotation(String quotation) {
		this.quotation = quotation;
	}

	@Column(name = "quotation_date", length = 50)
	public String getQuotationDate() {
		return this.quotationDate;
	}

	public void setQuotationDate(String quotationDate) {
		this.quotationDate = quotationDate;
	}

	@Column(name = "your_reference", length = 50)
	public String getYourReference() {
		return this.yourReference;
	}

	public void setYourReference(String yourReference) {
		this.yourReference = yourReference;
	}

	@Column(name = "salesperson", length = 50)
	public String getSalesperson() {
		return this.salesperson;
	}

	public void setSalesperson(String salesperson) {
		this.salesperson = salesperson;
	}

	@Column(name = "telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "supplying_vendor", length = 50)
	public String getSupplyingVendor() {
		return this.supplyingVendor;
	}

	public void setSupplyingVendor(String supplyingVendor) {
		this.supplyingVendor = supplyingVendor;
	}

	@Column(name = "customer", length = 50)
	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	@Column(name = "complete_delivery", length = 50)
	public String getCompleteDelivery() {
		return this.completeDelivery;
	}

	public void setCompleteDelivery(String completeDelivery) {
		this.completeDelivery = completeDelivery;
	}

	@Column(name = "gr_message", length = 50)
	public String getGrMessage() {
		return this.grMessage;
	}

	public void setGrMessage(String grMessage) {
		this.grMessage = grMessage;
	}

	@Column(name = "target_val_header", length = 50)
	public String getTargetValHeader() {
		return this.targetValHeader;
	}

	public void setTargetValHeader(String targetValHeader) {
		this.targetValHeader = targetValHeader;
	}

	@Column(name = "invoicing_party", length = 50)
	public String getInvoicingParty() {
		return this.invoicingParty;
	}

	public void setInvoicingParty(String invoicingParty) {
		this.invoicingParty = invoicingParty;
	}

	@Column(name = "address_number", length = 50)
	public String getAddressNumber() {
		return this.addressNumber;
	}

	public void setAddressNumber(String addressNumber) {
		this.addressNumber = addressNumber;
	}

	@Column(name = "country_sls_tax_no", length = 50)
	public String getCountrySlsTaxNo() {
		return this.countrySlsTaxNo;
	}

	public void setCountrySlsTaxNo(String countrySlsTaxNo) {
		this.countrySlsTaxNo = countrySlsTaxNo;
	}

	@Column(name = "vat_registration_no", length = 50)
	public String getVatRegistrationNo() {
		return this.vatRegistrationNo;
	}

	public void setVatRegistrationNo(String vatRegistrationNo) {
		this.vatRegistrationNo = vatRegistrationNo;
	}

	@Column(name = "reason_for_canc", length = 50)
	public String getReasonForCanc() {
		return this.reasonForCanc;
	}

	public void setReasonForCanc(String reasonForCanc) {
		this.reasonForCanc = reasonForCanc;
	}

	@Column(name = "document_number", length = 50)
	public String getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	@Column(name = "incomplete", length = 50)
	public String getIncomplete() {
		return this.incomplete;
	}

	public void setIncomplete(String incomplete) {
		this.incomplete = incomplete;
	}

	@Column(name = "down_payment", length = 50)
	public String getDownPayment() {
		return this.downPayment;
	}

	public void setDownPayment(String downPayment) {
		this.downPayment = downPayment;
	}

	@Column(name = "down_payt_percentage", length = 50)
	public String getDownPaytPercentage() {
		return this.downPaytPercentage;
	}

	public void setDownPaytPercentage(String downPaytPercentage) {
		this.downPaytPercentage = downPaytPercentage;
	}

	@Column(name = "down_payment_amount", length = 50)
	public String getDownPaymentAmount() {
		return this.downPaymentAmount;
	}

	public void setDownPaymentAmount(String downPaymentAmount) {
		this.downPaymentAmount = downPaymentAmount;
	}

	@Column(name = "due_date_for_down_payment", length = 50)
	public String getDueDateForDownPayment() {
		return this.dueDateForDownPayment;
	}

	public void setDueDateForDownPayment(String dueDateForDownPayment) {
		this.dueDateForDownPayment = dueDateForDownPayment;
	}

	@Column(name = "shipping_type", length = 50)
	public String getShippingType() {
		return this.shippingType;
	}

	public void setShippingType(String shippingType) {
		this.shippingType = shippingType;
	}

	@Column(name = "handover_location", length = 50)
	public String getHandoverLocation() {
		return this.handoverLocation;
	}

	public void setHandoverLocation(String handoverLocation) {
		this.handoverLocation = handoverLocation;
	}

	@Column(name = "shipping_conditions", length = 50)
	public String getShippingConditions() {
		return this.shippingConditions;
	}

	public void setShippingConditions(String shippingConditions) {
		this.shippingConditions = shippingConditions;
	}

}
