package com.udanti.finance.dao;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinanceInventory generated by hbm2java
 */
@Entity
@Table(name = "finance_inventory", catalog = "udnati")
public class FinanceInventory implements java.io.Serializable {

	private int inventoryId;
	private String companyCode;
	private String vendor;
	private String spGlTransType;
	private String specialGlInd;
	private Date clearingDate;
	private String clearingDocument;
	private String fiscalYear;
	private String documentNumber;
	private Date postingDate;
	private Date documentDate;
	private Date entryDate;
	private String currency;
	private String reference;
	private String documentType;
	private String postingPeriod;
	private String debitCreditInd;
	private String businessArea;
	private String taxCode;
	private String amount;
	private String taxAmount;
	private String purchasingDocument;
	private String item;
	private String glAccount;
	private String financialBudget;
	private String discountBase;
	private String casDiscountAmount;
	private String discountAmount;
	private String invoiceReference;
	private String lineItem;
	private String collectiveInvoice;
	private String paymentTransaction;
	private String tradingPartner;
	private String vatRegistrationNo;
	private String network;
	private String opertnTaskListNo;
	private String reverseClearing;
	private String costCenter;
	private String sequenceNumber;
	private String reversalFlag;
	private String generalLedgerCurrency;
	private String generalLedgerAmount;
	private String fundsCenter;
	private String fund;
	private Date referenceDate;
	private String negativePosting;
	private String payee;
	private String pmntCurrAmnt;
	private String penaltyCharge;
	private String reasonForLatePmnt;
	private String accountId;

	public FinanceInventory() {
	}

	public FinanceInventory(int inventoryId) {
		this.inventoryId = inventoryId;
	}

	public FinanceInventory(int inventoryId, String companyCode, String vendor,
			String spGlTransType, String specialGlInd, Date clearingDate,
			String clearingDocument, String fiscalYear, String documentNumber,
			Date postingDate, Date documentDate, Date entryDate,
			String currency, String reference, String documentType,
			String postingPeriod, String debitCreditInd, String businessArea,
			String taxCode, String amount, String taxAmount,
			String purchasingDocument, String item, String glAccount,
			String financialBudget, String discountBase,
			String casDiscountAmount, String discountAmount,
			String invoiceReference, String lineItem, String collectiveInvoice,
			String paymentTransaction, String tradingPartner,
			String vatRegistrationNo, String network, String opertnTaskListNo,
			String reverseClearing, String costCenter, String sequenceNumber,
			String reversalFlag, String generalLedgerCurrency,
			String generalLedgerAmount, String fundsCenter, String fund,
			Date referenceDate, String negativePosting, String payee,
			String pmntCurrAmnt, String penaltyCharge,
			String reasonForLatePmnt, String accountId) {
		this.inventoryId = inventoryId;
		this.companyCode = companyCode;
		this.vendor = vendor;
		this.spGlTransType = spGlTransType;
		this.specialGlInd = specialGlInd;
		this.clearingDate = clearingDate;
		this.clearingDocument = clearingDocument;
		this.fiscalYear = fiscalYear;
		this.documentNumber = documentNumber;
		this.postingDate = postingDate;
		this.documentDate = documentDate;
		this.entryDate = entryDate;
		this.currency = currency;
		this.reference = reference;
		this.documentType = documentType;
		this.postingPeriod = postingPeriod;
		this.debitCreditInd = debitCreditInd;
		this.businessArea = businessArea;
		this.taxCode = taxCode;
		this.amount = amount;
		this.taxAmount = taxAmount;
		this.purchasingDocument = purchasingDocument;
		this.item = item;
		this.glAccount = glAccount;
		this.financialBudget = financialBudget;
		this.discountBase = discountBase;
		this.casDiscountAmount = casDiscountAmount;
		this.discountAmount = discountAmount;
		this.invoiceReference = invoiceReference;
		this.lineItem = lineItem;
		this.collectiveInvoice = collectiveInvoice;
		this.paymentTransaction = paymentTransaction;
		this.tradingPartner = tradingPartner;
		this.vatRegistrationNo = vatRegistrationNo;
		this.network = network;
		this.opertnTaskListNo = opertnTaskListNo;
		this.reverseClearing = reverseClearing;
		this.costCenter = costCenter;
		this.sequenceNumber = sequenceNumber;
		this.reversalFlag = reversalFlag;
		this.generalLedgerCurrency = generalLedgerCurrency;
		this.generalLedgerAmount = generalLedgerAmount;
		this.fundsCenter = fundsCenter;
		this.fund = fund;
		this.referenceDate = referenceDate;
		this.negativePosting = negativePosting;
		this.payee = payee;
		this.pmntCurrAmnt = pmntCurrAmnt;
		this.penaltyCharge = penaltyCharge;
		this.reasonForLatePmnt = reasonForLatePmnt;
		this.accountId = accountId;
	}

	@Id
	@Column(name = "inventory_id", unique = true, nullable = false)
	public int getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(int inventoryId) {
		this.inventoryId = inventoryId;
	}

	@Column(name = "company_code", length = 50)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "vendor", length = 50)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "sp_gl_trans_type", length = 50)
	public String getSpGlTransType() {
		return this.spGlTransType;
	}

	public void setSpGlTransType(String spGlTransType) {
		this.spGlTransType = spGlTransType;
	}

	@Column(name = "special_gl_ind", length = 50)
	public String getSpecialGlInd() {
		return this.specialGlInd;
	}

	public void setSpecialGlInd(String specialGlInd) {
		this.specialGlInd = specialGlInd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "clearing_date", length = 0)
	public Date getClearingDate() {
		return this.clearingDate;
	}

	public void setClearingDate(Date clearingDate) {
		this.clearingDate = clearingDate;
	}

	@Column(name = "clearing_document", length = 50)
	public String getClearingDocument() {
		return this.clearingDocument;
	}

	public void setClearingDocument(String clearingDocument) {
		this.clearingDocument = clearingDocument;
	}

	@Column(name = "fiscal_year", length = 50)
	public String getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(String fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "document_number", length = 50)
	public String getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "posting_date", length = 0)
	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "document_date", length = 0)
	public Date getDocumentDate() {
		return this.documentDate;
	}

	public void setDocumentDate(Date documentDate) {
		this.documentDate = documentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_date", length = 0)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "currency", length = 50)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "reference", length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "document_type", length = 50)
	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	@Column(name = "posting_period", length = 50)
	public String getPostingPeriod() {
		return this.postingPeriod;
	}

	public void setPostingPeriod(String postingPeriod) {
		this.postingPeriod = postingPeriod;
	}

	@Column(name = "debit_credit_ind.", length = 50)
	public String getDebitCreditInd() {
		return this.debitCreditInd;
	}

	public void setDebitCreditInd(String debitCreditInd) {
		this.debitCreditInd = debitCreditInd;
	}

	@Column(name = "business_area", length = 50)
	public String getBusinessArea() {
		return this.businessArea;
	}

	public void setBusinessArea(String businessArea) {
		this.businessArea = businessArea;
	}

	@Column(name = "tax_code", length = 50)
	public String getTaxCode() {
		return this.taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	@Column(name = "amount", length = 50)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "tax_amount", length = 50)
	public String getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(String taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "purchasing_document", length = 50)
	public String getPurchasingDocument() {
		return this.purchasingDocument;
	}

	public void setPurchasingDocument(String purchasingDocument) {
		this.purchasingDocument = purchasingDocument;
	}

	@Column(name = "item", length = 50)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "gl_account", length = 50)
	public String getGlAccount() {
		return this.glAccount;
	}

	public void setGlAccount(String glAccount) {
		this.glAccount = glAccount;
	}

	@Column(name = "financial_budget", length = 50)
	public String getFinancialBudget() {
		return this.financialBudget;
	}

	public void setFinancialBudget(String financialBudget) {
		this.financialBudget = financialBudget;
	}

	@Column(name = "discount_base", length = 50)
	public String getDiscountBase() {
		return this.discountBase;
	}

	public void setDiscountBase(String discountBase) {
		this.discountBase = discountBase;
	}

	@Column(name = "cas_discount_amount", length = 50)
	public String getCasDiscountAmount() {
		return this.casDiscountAmount;
	}

	public void setCasDiscountAmount(String casDiscountAmount) {
		this.casDiscountAmount = casDiscountAmount;
	}

	@Column(name = "discount_amount", length = 50)
	public String getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(String discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "invoice_reference", length = 50)
	public String getInvoiceReference() {
		return this.invoiceReference;
	}

	public void setInvoiceReference(String invoiceReference) {
		this.invoiceReference = invoiceReference;
	}

	@Column(name = "line_item", length = 50)
	public String getLineItem() {
		return this.lineItem;
	}

	public void setLineItem(String lineItem) {
		this.lineItem = lineItem;
	}

	@Column(name = "collective_invoice", length = 50)
	public String getCollectiveInvoice() {
		return this.collectiveInvoice;
	}

	public void setCollectiveInvoice(String collectiveInvoice) {
		this.collectiveInvoice = collectiveInvoice;
	}

	@Column(name = "payment_transaction", length = 50)
	public String getPaymentTransaction() {
		return this.paymentTransaction;
	}

	public void setPaymentTransaction(String paymentTransaction) {
		this.paymentTransaction = paymentTransaction;
	}

	@Column(name = "trading_partner", length = 50)
	public String getTradingPartner() {
		return this.tradingPartner;
	}

	public void setTradingPartner(String tradingPartner) {
		this.tradingPartner = tradingPartner;
	}

	@Column(name = "vat_registration_no", length = 50)
	public String getVatRegistrationNo() {
		return this.vatRegistrationNo;
	}

	public void setVatRegistrationNo(String vatRegistrationNo) {
		this.vatRegistrationNo = vatRegistrationNo;
	}

	@Column(name = "network", length = 50)
	public String getNetwork() {
		return this.network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	@Column(name = "opertn_task_list_no", length = 50)
	public String getOpertnTaskListNo() {
		return this.opertnTaskListNo;
	}

	public void setOpertnTaskListNo(String opertnTaskListNo) {
		this.opertnTaskListNo = opertnTaskListNo;
	}

	@Column(name = "reverse_clearing", length = 50)
	public String getReverseClearing() {
		return this.reverseClearing;
	}

	public void setReverseClearing(String reverseClearing) {
		this.reverseClearing = reverseClearing;
	}

	@Column(name = "cost_center", length = 50)
	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "sequence_number", length = 50)
	public String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(String sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Column(name = "reversal_flag", length = 50)
	public String getReversalFlag() {
		return this.reversalFlag;
	}

	public void setReversalFlag(String reversalFlag) {
		this.reversalFlag = reversalFlag;
	}

	@Column(name = "general_ledger_currency", length = 50)
	public String getGeneralLedgerCurrency() {
		return this.generalLedgerCurrency;
	}

	public void setGeneralLedgerCurrency(String generalLedgerCurrency) {
		this.generalLedgerCurrency = generalLedgerCurrency;
	}

	@Column(name = "general_ledger_amount", length = 50)
	public String getGeneralLedgerAmount() {
		return this.generalLedgerAmount;
	}

	public void setGeneralLedgerAmount(String generalLedgerAmount) {
		this.generalLedgerAmount = generalLedgerAmount;
	}

	@Column(name = "funds_center", length = 50)
	public String getFundsCenter() {
		return this.fundsCenter;
	}

	public void setFundsCenter(String fundsCenter) {
		this.fundsCenter = fundsCenter;
	}

	@Column(name = "fund", length = 50)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reference_date", length = 0)
	public Date getReferenceDate() {
		return this.referenceDate;
	}

	public void setReferenceDate(Date referenceDate) {
		this.referenceDate = referenceDate;
	}

	@Column(name = "negative_posting", length = 50)
	public String getNegativePosting() {
		return this.negativePosting;
	}

	public void setNegativePosting(String negativePosting) {
		this.negativePosting = negativePosting;
	}

	@Column(name = "payee", length = 50)
	public String getPayee() {
		return this.payee;
	}

	public void setPayee(String payee) {
		this.payee = payee;
	}

	@Column(name = "pmnt_curr_amnt", length = 50)
	public String getPmntCurrAmnt() {
		return this.pmntCurrAmnt;
	}

	public void setPmntCurrAmnt(String pmntCurrAmnt) {
		this.pmntCurrAmnt = pmntCurrAmnt;
	}

	@Column(name = "penalty_charge", length = 50)
	public String getPenaltyCharge() {
		return this.penaltyCharge;
	}

	public void setPenaltyCharge(String penaltyCharge) {
		this.penaltyCharge = penaltyCharge;
	}

	@Column(name = "reason_for_late_pmnt", length = 50)
	public String getReasonForLatePmnt() {
		return this.reasonForLatePmnt;
	}

	public void setReasonForLatePmnt(String reasonForLatePmnt) {
		this.reasonForLatePmnt = reasonForLatePmnt;
	}

	@Column(name = "account_id", length = 50)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

}
